import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { ThemeProvider } from "next-themes"
import Footer from "./components/Home/Footer";
import Header from "./components/Header";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bitsframe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}> 
        <Header/>
       <ThemeProvider attribute="class" defaultTheme="system" enableSystem>

           
        
        {children}
        <Footer/>
      
        </ThemeProvider>
      </body>
    </html>
  );
}